name: Build and Deploy Docker Image

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release Tag"
        required: true
      is_latest:
        description: "Tag as latest"
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Release Tag
        id: set-tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "Release triggered with tag: ${{ github.event.release.tag_name }}"
            echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
            # Automatically tag as latest during a release event if needed
            LATEST_TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
            if [[ "${{ github.event.release.tag_name }}" == "$LATEST_TAG" ]]; then
              echo "IS_LATEST=true" >> $GITHUB_ENV
            else
              echo "IS_LATEST=false" >> $GITHUB_ENV
            fi
          else
            echo "Manual trigger with user input tag: ${{ github.event.inputs.release_tag }}"
            echo "RELEASE_TAG=${{ github.event.inputs.release_tag }}" >> $GITHUB_ENV
            echo "IS_LATEST=${{ github.event.inputs.is_latest }}" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/$(basename ${{ github.repository }}):${{ env.RELEASE_TAG }} \
            $([ "${{ env.IS_LATEST }}" == "true" ] && echo "-t ${{ secrets.DOCKERHUB_USERNAME }}/$(basename ${{ github.repository }}):latest") \
            --push .
